server:
  directory: c:/temp
  port: 7878
  packages: io.orthrus.directory   
   
directory:
   store: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-directory/store/user

jmx:
   login: admin
   password: admin
   port: 7879

logging:
  level:
    root: INFO        
