server:
  environment: local
  name: directory
  directory: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-directory
  port: 8383
  packages: io.orthrus.directory,io.orthrus.store,io.orthrus.jmx

jmx:
   login: admin
   password: password12
   port: 5777

tuple:
   path: ${server.directory}/store/${server.environment}
   name: ${server.name}
   packages: io.orthrus
   port: 2${server.port}  

zookeeper:   
   hosts: localhost:2181

logging:
  level:
    root: INFO        
