server:
  directory: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-directory
  port: 8383
  packages: io.orthrus.directory   
   
directory:
   store: ${server.directory}/store/user

jmx:
   login: admin
   password: password12
   port: 5777

logging:
  level:
    root: INFO        
