server:
  name: directory
  directory: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-directory
  port: 8383
  packages: io.orthrus.directory,io.orthrus.store   

jmx:
   login: admin
   password: password12
   port: 5777

tuple:
   path: ${server.directory}/store/${spring.profiles.active}
   name: ${server.name}
   packages: io.orthrus
   port: 2${server.port}  

logging:
  level:
    root: INFO        
