server:
  environment: prod
  directory: /apps/sso/current
      
login:
   url:
      directory: http://prodapp1:8383/ 
   token-store:
      path: /var/creds/www.orthrus.io.pfx 
 
mail:
   credentials: /var/creds/smtp.properties 
      
tuple:
   remote: @tuple.remote@        
