server:
  name: terminal
  environment: local
  directory: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-terminal
  port: 8899
  packages: io.orthrus.terminal,io.orthrus.jmx  
   
jmx:
   login: admin
   password: password12
   port: 9955   
   
terminal:
   host: localhost   
   
zookeeper:   
   hosts: localhost:${zookeeper.clientPort}
   dataDir: ${server.directory}/data
   clientPort: 2181
   maxClientCnxns: 0   
   initLimit: 5
   syncLimit: 2
   server.1: localhost:2888:3888
   