server:
  name: terminal
  environment: local
  directory: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-terminal
  port: 8899
  packages: io.orthrus.terminal   
   
jmx:
   login: admin
   password: password12
   port: 9955   
   
terminal:
   host: localhost   
   
zookeeper:   
   hosts: localhost:${zookeeper.clientPort}
   dataDir: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-terminal/data
   clientPort: 2181
   maxClientCnxns: 0   
