server:
  directory: /apps/rp/current
  port: 7979
  packages: io.orthrus.gateway   
      
gateway:   
  debug: false
  domain: www.orthrus.io
  resources: /apps/rp/current 
  plan: ${gateway.resources}/etc/plan.json  
  key-store: ${gateway.resources}/etc/${gateway.domain}.pfx     

logging:
  level:
    root: INFO        

