server:
  directory: c:/temp
  port: 7979
  packages: io.orthrus.sso   
      
gateway:   
  plan: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-gateway/etc/plan.json   
  resources: C:/Work/development/snapscript/snap-archive/snap-server/orthrus-gateway   

logging:
  level:
    root: INFO        

