server:
  environment: prod
  directory: /apps/rp/current  
      
gateway:   
  debug: false
  domain: www.orthrus.io
  creds: /var/creds    
  resources: ${server.directory}
  plan: ${server.directory}/etc/plan.json  
  key-store: /var/creds/${gateway.domain}/${gateway.domain}.pfx
       
zookeeper:   
   hosts: prodapp1:2181,prodapp2:2181    

logging:
  level:
    root: INFO        

