server:
  directory: /apps/rp/current
  port: 7979
  packages: io.orthrus.gateway   
      
gateway:   
  debug: false
  domain: www.orthrus.io
  plan: /apps/rp/current/etc/orthrus.json   
  resources: /apps/rp/current   

logging:
  level:
    root: INFO        

