server:
  directory: /apps/rp/current  
      
gateway:   
  debug: false
  domain: www.orthrus.io
  resources: ${server.directory}
  plan: ${server.directory}/etc/plan.json  
  key-store: /var/creds/${gateway.domain}.pfx     

logging:
  level:
    root: INFO        

